backend:
  name: github
  repo: Alvanza0904/alvanomodajaecoo
  branch: main
  base_url: https://decap-proxy.freftialvanza0904.workers.dev
  auth_endpoint: /auth

media_folder: assets/images

collections:
  - name: berita
    label: Berita
    folder: berita
    create: true
    fields:
      - { label: Judul, name: title, widget: string }
      - { label: Tanggal, name: date, widget: datetime }
      - { label: Konten, name: body, widget: markdown }
